import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';
import 'react-time-picker/dist/TimePicker.css';
import 'react-clock/dist/Clock.css';
import { ThemeProvider } from '@/providers/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import QueryClientProvider from '@/providers/query-client-provider';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

const geistSans = localFont({
   src: '../fonts/GeistVF.woff',
   variable: '--font-geist-sans',
   weight: '100 900'
});
const geistMono = localFont({
   src: '../fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
   weight: '100 900'
});

export const metadata: Metadata = {
   title: 'المنصة الرقمية ',
   description: 'Generated by create next app',
   icons: '/logoINSS.png'
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en' dir='rtl'>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <QueryClientProvider>
               <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                  <NuqsAdapter>{children}</NuqsAdapter>
                  <Toaster />
               </ThemeProvider>
            </QueryClientProvider>
         </body>
      </html>
   );
}
