export const columnsAcademicAchievement: { label: string; value: string; className?: string }[] = [
    { label: 'الرقم الوظيفي', value: 'jobCode', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'رقم الاضبارة', value: 'typeOfServiceId', className: 'font-bold' },
    { label: "العنوان الوظيفي السابق", value: 'jobTitleFromName', className: 'font-bold' },
    { label: "الدرجة السابقة", value: 'degreeFromName', className: 'font-bold' },
    { label: "الفئة السابقة", value: 'jobCategoryFromName', className: 'font-bold' },
    { label: "الوصف الوظيفي السابق", value: 'jobDescriptionFromName', className: 'font-bold' },
    { label: "الدرجة الجديدة", value: 'degreeToName', className: 'font-bold' },
    { label: "تاريخ تسكين الدرجة ", value: 'dueDateDegree', className: 'font-bold' },
    { label: "تاريخ تسكين الفئة ", value: 'dueDateCategory', className: 'font-bold' },
    { label: "العنوان الوظيفي الجديد", value: 'jobTitleToName', className: 'font-bold' },
    { label: "الفئة الجديدة", value: 'jobCategoryToName', className: 'font-bold' },
    { label: 'رقم الامر الاداري', value: 'orderNo', className: 'font-bold' },
    { label: 'تاريخ الامر الاداري', value: 'orderDate', className: 'font-bold' },
    { label: 'المرفقات', value: 'attachments', className: 'font-bold' },
    { label: 'الملاحظات', value: 'note', className: 'font-bold' },
    { label: 'الحالة', value: 'statusName', className: 'font-bold' },
];