export const columnsAffiliatesFromOrg: { label: string; value: string; className?: string }[] = [
    { label: 'الرقم الوظيفي', value: 'jobCode', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'رقم الأمر الإداري', value: 'orderNo', className: 'font-bold' },
    { label: 'تاريخ الأمر الإداري', value: 'orderDate', className: 'font-bold' },
    { label: 'المنسب منها', value: 'affiliateFrom', className: 'font-bold' },
    { label: 'المنسب اليها', value: 'affiliateTo', className: 'font-bold' },
    { label: 'نوع الامر', value: 'orderType', className: 'font-bold' },
    { label: 'مدة التنسيب بالاشهر', value: 'countOfMonths', className: 'font-bold' },
    { label: 'رقم كتاب الانفكاك', value: 'disengagementLetterNumber', className: 'font-bold' },
    { label: 'تاريخ كتاب الانفكاك', value: 'disengagementLetterDate', className: 'font-bold' },
    { label: 'تاريخ الانفكاك', value: 'disengagementDate', className: 'font-bold' },
    { label: 'رقم كتاب المباشرة', value: 'startLetterNumber', className: 'font-bold' },
    { label: 'تاريخ كتاب المباشرة', value: 'startLetterDate', className: 'font-bold' },
    { label: 'تاريخ المباشرة', value: 'startDate', className: 'font-bold' },
    { label: 'رقم كتاب التكليف', value: 'endAssignmentLetterNumber', className: 'font-bold' },
    { label: 'تاريخ كتاب التكليف', value: 'endAssignmentLetterDate', className: 'font-bold' },
    { label: 'المرفقات', value: 'attachments', className: 'font-bold' },
    { label: 'الملاحظات', value: 'note', className: 'font-bold' },
    { label: 'الحالة', value: 'status', className: 'font-bold' },
    { label: 'الإجراءات', value: 'actions', className: 'font-bold' },
];