export const columnsCourse: { label: string; value: string; className?: string }[] = [
    { label: '#', value: 'id', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'رقم الاضبارة', value: 'lotNumber', className: 'font-bold' },
    { label: 'الرقم الوظيفي', value: 'jobCode', className: 'hidden md:table-cell font-bold' },
    { label: 'اسم الدورة', value: 'title', className: 'hidden md:table-cell font-bold' },
    { label: 'مكان الدورة', value: 'place', className: 'hidden md:table-cell font-bold' },
    { label: 'الجهة المقيمة', value: 'residentEntity', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم كتاب الدورة', value: 'courseOrderNo', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ كتاب الدورة', value: 'courseOrderDate', className: 'hidden md:table-cell font-bold' },
    { label: 'مدة الدورة', value: 'courseDurationInDays', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ بدء الدورة', value: 'startDate', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ انتهاء الدورة', value: 'endDate', className: 'hidden md:table-cell font-bold' },
    // { label: 'رقم كتاب الترشيح', value: 'nominationOrderNo', className: 'hidden md:table-cell font-bold' },
    // { label: 'تاريخ كتاب الترشيح', value: 'nominationOrderDate', className: 'hidden md:table-cell font-bold' },
    { label: 'النتيجة ', value: 'evaluation', className: 'hidden md:table-cell font-bold' },
    // { label: 'رقم كتاب الانفكاك', value: 'releaseOrderNo', className: 'hidden md:table-cell font-bold' },
    // { label: 'تاريخ كتاب الانفكاك', value: 'releaseOrderDate', className: 'hidden md:table-cell font-bold' },
    // { label: 'تاريخ الانفكاك', value: 'releaseDate', className: 'hidden md:table-cell font-bold' },
    // { label: 'رقم كتاب المباشرة', value: 'hireOrderNo', className: 'hidden md:table-cell font-bold' },
    // { label: 'تاريخ كتاب المباشرة', value: 'hireOrderDate', className: 'hidden md:table-cell font-bold' },
    // { label: 'تاريخ المباشرة', value: 'hireDate', className: 'hidden md:table-cell font-bold' },
    { label: 'المرفقات', value: 'attachment', className: 'hidden md:table-cell font-bold' },
    // { label: 'الملاحظات', value: 'note', className: 'hidden md:table-cell font-bold' },
];