export const columnsRetirement: { label: string; value: string; className?: string }[] = [
    { label: '#', value: 'id', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'رقم الاضبارة', value: 'lotNumber', className: 'font-bold' },
    { label: 'رقم الاحصائي', value: 'statisticalIndex', className: 'hidden md:table-cell font-bold' },
    { label: 'التحصيل الدراسي', value: 'academicAchievementName', className: 'hidden md:table-cell font-bold' },
    { label: 'الرقم الوظيفي', value: 'jobCode', className: 'hidden md:table-cell font-bold' },
    { label: 'الدائرة', value: 'directorateName', className: 'hidden md:table-cell font-bold' },
    { label: 'المديرية', value: 'subDirectorateName', className: 'hidden md:table-cell font-bold' },
    { label: 'الدرجة الوظيفية', value: 'jobDegreeName', className: 'hidden md:table-cell font-bold' },
    { label: 'الفئة الوظيفية', value: 'jobCategoryName', className: 'hidden md:table-cell font-bold' },
    { label: 'العنوان الوظيفي', value: 'jobTitleName', className: 'hidden md:table-cell font-bold' },
    { label: 'قرار تثبيت العمر', value: 'decisionToFixAge', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ الخروج من الخدمة', value: 'endDateOfService', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ الميلاد', value: 'birthdate', className: 'hidden md:table-cell font-bold' },
    { label: 'سن التقاعد', value: 'retirementDate', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم الامر الاداري باضافة الخدمة', value: 'administrativeOrderNo', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ الامر الاداري باضافة الخدمة', value: 'administrativeOrderDate', className: 'hidden md:table-cell font-bold' },
    { label: 'مفصول سياسيا', value: 'isPoliticallyDismissed', className: 'hidden md:table-cell font-bold' },
    // { label: 'اضافة خدمة', value: '', className: 'hidden md:table-cell font-bold' },
    { label: 'الحالة', value: 'statusName', className: 'hidden md:table-cell font-bold' },
    { label: 'المرفقات', value: 'attachments', className: 'hidden md:table-cell font-bold' },

    { label: 'الملاحظات', value: 'note', className: 'hidden md:table-cell font-bold' },
];