export const columnsCertificateCalculation: { label: string; value: string; className?: string }[] = [
    { label: 'الرقم الوظيفي', value: 'jobCode', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'رقم الاضبارة', value: 'typeOfServiceId', className: 'font-bold' },
    { label: 'العنوان الوظيفي السابق', value: 'oldJobTitle', className: 'font-bold' },
    { label: 'الدرجة السابقة', value: 'oldDegree', className: 'font-bold' },
    { label: 'الفئة السابقة', value: 'oldCategory', className: 'font-bold' },
    { label: 'الدرجة الجديدة', value: 'degreeToId', className: 'font-bold' },
    { label: 'العنوان الوظيفي الجديد', value: 'jobTitleToId', className: 'font-bold' },
    { label: 'الفئة الجديدة', value: 'jobCategoryToId', className: 'font-bold' },
    { label: 'تاريخ تسكين الدرجة', value: 'degreePlacementDate', className: 'font-bold' },
    { label: 'رقم الامر الاداري', value: 'orderNo', className: 'font-bold' },
    { label: 'تاريخ الامر الاداري', value: 'orderDate', className: 'font-bold' },
    { label: 'المرفقات', value: 'attachments', className: 'font-bold' },
    { label: 'الملاحظات', value: 'note', className: 'font-bold' },
    { label: 'الحالة', value: 'status', className: 'font-bold' },
];