export const columnsReports: { label: string; value: string; className?: string }[] = [
    { label: 'الرقم الوظيفي', value: 'fileNumber', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'الدرجة الوظيفية', value: 'jobDegreeName', className: 'font-bold' },
    { label: 'العنوان الوظيفي', value: 'jobTitleName', className: 'font-bold' },
    { label: 'الامر الصادر بموجبه أخر ترفيع', value: 'orderNo', className: 'font-bold' },
    { label: 'تاريخ', value: 'orderDate', className: 'font-bold' },
    { label: 'ارقام أوامر كتب الشكر', value: 'thanksOrderNo', className: 'font-bold' },
    { label: 'تاريخ كتب الشكر', value: 'thanksOrderDate', className: 'font-bold' },
    { label: 'العقوبات', value: 'penalties', className: 'font-bold' },
    { label: 'تاريخ العقوبة', value: 'penaltiesDate', className: 'font-bold' },
    { label: 'الاجازات بدون راتب', value: 'leaveWithoutSalary', className: 'font-bold' },
    { label: 'من تاريخ', value: 'fromDate', className: 'font-bold' },
    { label: 'الى تاريخ', value: 'toDate', className: 'font-bold' },
    { label: 'الدرجة الجديدة', value: 'newJobDegreeName', className: 'font-bold' },
    { label: 'التحصيل الدراسي', value: 'academicAchievement', className: 'font-bold' },
    // { label: 'العنوان الجديد', value: 'newJobTitleName', className: 'font-bold' },
    { label: 'تارخ الاستحقاق', value: 'dueDate', className: 'font-bold' },
    { label: 'تفاصيل الحساب', value: 'actions', className: 'font-bold' }
];