export const columnsEducationInfo: { label: string; value: string; className?: string }[] = [
    { label: '#', value: 'id', className: 'font-bold' },
    { label: 'البلد', value: 'country', className: 'hidden md:table-cell font-bold' },
    { label: 'عنوان الوثيقة دراسية', value: 'originalDocument', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم الوثيقة', value: 'documentNo', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ الوثيقة', value: 'documentDate', className: 'hidden md:table-cell font-bold' },
    { label: 'الجهة المرسلة للوثيقة', value: 'documentSender', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ الارسال', value: 'documentSendDate', className: 'hidden md:table-cell font-bold' },
    { label: 'التحصيل الدراسي', value: 'academicAchievementName', className: 'hidden md:table-cell font-bold' },
    { label: 'التخصص', value: 'academicFieldName', className: 'hidden md:table-cell font-bold' },
    { label: 'التخصص الدقيق', value: 'preciseAcademicFieldName', className: 'hidden md:table-cell font-bold' },
    { label: 'سنة التخرج', value: 'graduationYear', className: 'hidden md:table-cell font-bold' },
    { label: 'نوع الدراسة ', value: 'studyTypeName', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ بدأ الدراسة', value: 'startDate', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ نهاية الدراسة', value: 'endDate', className: 'hidden md:table-cell font-bold' },
    { label: 'هل الشهادة ممنوحة بعد التعيين', value: 'isDuringRecruitment', className: 'hidden md:table-cell font-bold' },
    { label: 'تاكيد صحة الصدور ', value: 'isdocumentVerify', className: 'hidden md:table-cell font-bold' },
    { label: 'الملاحظات', value: 'note', className: 'hidden md:table-cell font-bold' },
    { label: 'المرفقات', value: 'attachment', className: 'hidden md:table-cell font-bold' },
    // { label: 'الأجرائات', value: 'Actions', className: 'w-44 hidden md:table-cell font-bold' },
];