export const columnsTrainingCourses: { label: string; value: string; className?: string }[] = [
    { label: '#', value: 'id', className: 'font-bold' },
    { label: 'اسم الدورة', value: 'title', className: 'hidden md:table-cell font-bold' },
    { label: 'الجهة المقيمة', value: 'residenten', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم كتاب الدورة', value: 'coursbookNo', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ كتاب الدورة', value: 'coursbookDate', className: 'hidden md:table-cell font-bold' },
    { label: 'مدة الدورة', value: 'durationofthecourse', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ بدء الدورة', value: 'startDate', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ انتهاء الدورة', value: 'endDate', className: 'hidden md:table-cell font-bold' },
    { label: 'مكان الدورة', value: 'place', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم كتاب الترشيح', value: 'nominationletternum', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ كتاب الترشيح', value: 'nominationletterdate', className: 'hidden md:table-cell font-bold' },
    { label: 'النتيجة', value: 'evaluation', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم كتاب الانفكاك', value: 'dissolutionbooknum', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ كتاب الانفكاك', value: 'dissolutionbookdate', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ الانفكاك ', value: 'dissolutiondate', className: 'hidden md:table-cell font-bold' },
    { label: 'رقم كتاب المباشرة', value: 'Directbooknum', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ كتاب المباشرة', value: 'Directbookdate', className: 'hidden md:table-cell font-bold' },
    { label: 'تاريخ المباشرة', value: 'Directdate', className: 'hidden md:table-cell font-bold' },
    { label: 'الحالة', value: 'statusName', className: 'hidden md:table-cell font-bold' },
    // { label: 'الأجرائات', value: 'Actions', className: 'w-44 hidden md:table-cell font-bold' },
];