export const columnsAccelerateAchievement: { label: string; value: string; className?: string }[] = [
    { label: 'الرقم الوظيفي', value: 'jobCode', className: 'font-bold' },
    { label: 'اسم الموظف', value: 'fullName', className: 'font-bold' },
    { label: 'رقم الاضبارة', value: 'typeOfServiceId', className: 'font-bold' },
    { label: 'العنوان الوظيفي السابق', value: 'jobTitleFromId', className: 'font-bold' },
    { label: 'الوصف الوظيفي السابق', value: 'jobDescriptionFromId', className: 'font-bold' },
    { label: 'الدرجة السابقة', value: 'jobDegreeFromId', className: 'font-bold' },
    { label: 'الفئة السابقة', value: 'jobCategoryFromId', className: 'font-bold' },
    { label: "تاريخ تسكين الدرجة السابق", value: 'oldDegreeDueDate', className: 'font-bold' },
    { label: "تاريخ تسكين الفئة السابق", value: 'oldCategoryDueDate', className: 'font-bold' },
    { label: 'الدرجة الجديدة', value: 'jobDegreeToName', className: 'font-bold' },
    { label: 'العنوان الوظيفي الجديد', value: 'jobTitleToName', className: 'font-bold' },
    { label: 'الوصف الوظيفي الجديد', value: 'jobDescriptionToName', className: 'font-bold' },
    { label: 'الفئة الجديدة', value: 'jobCategoryToName', className: 'font-bold' },
    { label: 'تاريخ تسكين الدرجة الجديد', value: 'newDegreeDueDate', className: 'font-bold' },
    { label: 'تاريخ تسكين الفئة الجديد', value: 'newCategoryDueDate', className: 'font-bold' },
    { label: 'رقم الامر الاداري', value: 'orderNo', className: 'font-bold' },
    { label: 'تاريخ الامر الاداري', value: 'orderDate', className: 'font-bold' },
    { label: 'المرفقات', value: 'attachments', className: 'font-bold' },
    { label: 'الملاحظات', value: 'note', className: 'font-bold' },
    { label: 'الحالة', value: 'statusName', className: 'font-bold' },
    { label: 'الإجراءات', value: 'actions', className: 'font-bold' },
];